### ISSUE TITLE
Engine flags issues under .git

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/codeclimate-phpcodesniffer#14]
There seems to be a "this is not a PHP file" check and it's generating issues for files under `.git`. This 1) doesn't make sense and 2) causes problems when we attempt to render these issues on the site.

**Comment by pbrisbin** [comment]
The fix is likely to add `and $f !== '.git'` [here](https://github.com/codeclimate/codeclimate-phpcodesniffer/blob/master/Runner.php#L25).

**Comment by opalenet-yann** [comment]
Noticed a similar issues, a temporary fixed seems to add into the codeclimate.yml the phpcondesniffer config 
```
phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
```
