### ISSUE TITLE
WordPress-VIP issues display when config is set to "WordPress"

### ISSUE THREAD

**Issue by sfgarza** [codeclimate/codeclimate-phpcodesniffer#37]
I have my codeclimate config set up like this
```
phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
```
But WordPress-VIP issues are showing up codeclimate

**Comment by bhubbard** [comment]
+1

**Comment by dblandin** [comment]
Hey @sfgarza,

Happy to hear that you're checking out the new Wordpress support!

As it's mentioned in the [WordPress-Coding-Standards README][], the WordPress standard includes the complete set with all of the sniffs in the project. This includes WordPress-Core, Wordpress-Docs, Wordpress-Extra, and Wordpress-VIP.

If you don't want Wordpress-VIP issues, you should choose another standard option.

This can be a single entry, like "Wordpress-Core", or a comma-separate list, omitting "Wordpress-VIP":

```yaml
phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core,Wordpress-Docs,Wordpress-Extra"
```

[WordPress-Coding-Standards README]: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#standards-subsets
