### ISSUE TITLE
Autofix using phpcbf (?)

### ISSUE THREAD

**Issue by soderlind** [codeclimate/codeclimate-phpcodesniffer#41]
Since `phpcbf` is included, how about adding the option `autofix` to the config and have phpcbf fix many of the coding standard errors ?

```yml
engines:
    phpcodesniffer:
       enabled: true
       config:
          standard: "WordPress-Core"
       autofix: true
```
