### ISSUE TITLE
configuration not being honored

### ISSUE THREAD

**Issue by ablyler** [codeclimate/codeclimate-phpcodesniffer#8]
I'm trying to use a custom configuration via my .codeclimate.yml that is in the root of my repo that contains:

```
exclude_paths:
 - "/build"
 - "/doc_generator"
 - "/modules"
 - "/resource"
 - "/tests"
engines:
  phpcodesniffer:
    enabled: true
    config:
      - file_extensions: "php"
      - standard: ["/code/modules/code-standards/company/ruleset.xml"]
ratings:
  paths:
  - "**.php"
```

However, when I look at the running processes while running `codeclimate analyze`, I see:

```
 4327 ?        Ss     0:00  \_ /bin/sh /usr/src/app/bin/codeclimate-phpcodesniffer
 4333 ?        S      0:00      \_ php /usr/src/app/bin/../engine.php
 4334 ?        S      0:00          \_ sh -c ./vendor/bin/phpcs --report=json --ignore= --standard=PSR1,PSR2 /code
 4335 ?        R      0:01              \_ php ./vendor/bin/phpcs --report=json --ignore= --standard=PSR1,PSR2 /code
````

**Comment by ablyler** [comment]
Also, this might be a hint:

{code}
$ codeclimate validate-config
WARNING in engines: unexpected key "config", dropping
{code}

**Comment by pbrisbin** [comment]
Sorry about this! We recently made our config parser more strict and accidentally made it reject this valid key. We'll do our best to get that fixed soon.

**Comment by GordonDiggs** [comment]
@ablyler 

Hey!
I just pushed some changes that should resolve this issue. Here's what you need to do:

1. Update the codeclimate CLI. If you're using homebrew on OS X, you can do this with `brew update && brew upgrade codeclimate`.
2. Update your config file to be the following:

    ```yaml
    exclude_paths:
     - "build/**/*"
     - "doc_generator/**/*"
     - "modules/**/*"
     - "resource/**/*"
     - "tests/**/*"
    engines:
      phpcodesniffer:
        enabled: true
        config:
          file_extensions: "php"
          standard: "/code/modules/code-standards/company/ruleset.xml"
    ratings:
      paths:
      - "**/*.php"
    ```

    I changed a few things here:
    - Your exclude paths were absolute instead of relative. These new globs will exclude all files in those directories and their subdirectories
    - I updated the phpcodesniffer config. Our README was actually wrong on this one and I've updated it there as well.
    - Applied a similar glob fix to the ratings paths.
3. Re-run `codeclimate analyze`. You should have the correct config now.

If this doesn't work for you, let me know and I can help debug more!
